baseurl: ""
title: "Optimistic Futures"
description: "A simple list of articles"
theme: jekyll-theme-minimal # Optional: GitHub’s minimal theme
collections:
  futures:
    output: true
    permalink: /futures/:slug/